name: Tests

on: 
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4

      - name: instatll dependencies
        run: |
          pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: run Tests
        Run: |
          pytest
        
