name: Tests

on: 
  push:
    branches: 
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: instatll dependencies
        run: |
          pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: run Tests
        run: |
          pytest

  

  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: buld docker image
        run: docker build . 
  
        
